name: Load Testing Action
description: 'Run load tests on the Django codebase'
runs:
  using: 'composite'
  steps:
    - name: Install locust
      run: pip install locust
      shell: bash

    - name: Run locust
      run: locust -f locustfile.py --host https://dev.guestbook.com
      shell: bash