name: Python Linting

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pylint
      run: |
        pip install pylint
        pylint_output=$(pylint $(git ls-files '*.py'))
        echo "$pylint_output"
        score=$(echo "$pylint_output" | grep 'Your code has been rated at' | awk '{print $7}' | sed 's/\/10//')
        echo "Pylint score: $score"
        if (( $(echo "$score < 8.0" | bc -l) )); then
          echo "Pylint score is below 8.0, failing the build"
          exit 1
        fi
